// Input: path to directory of .ttf font files
// Output: path to an output subdirectory of `src`
// Usage:
// node scripts/copy-fonts.mjs ../../vendor/urw-core35-fonts ./src/vendored-fonts

import { join, basename } from 'node:path';
import { readdir, readFile, writeFile } from 'node:fs/promises';

let inputDir = process.argv[2];
if(inputDir.startsWith('./')) {
  inputDir = inputDir.substring(2);
}
const outputDir = process.argv[3];

const dirents = await readdir(inputDir, { withFileTypes: true });

// TODO: just restrict to the 14 PDF base font equivalents?

for (const dirent of dirents) {
  const res = join(inputDir, dirent.name);
  if (dirent.name.endsWith(".ttf")) {
    const outputFile = join(outputDir, `${dirent.name}.js`);
    const ttfBytes = await readFile(res);
    const ttfString = ttfBytes.toString('base64');

    const jsString = `// AUTOGENERATED\nexport const ttfBytes = '${ttfString}';`;
    await writeFile(outputFile, jsString);
  }
}
