[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pluot_core"
version = "0.1.23"
requires-python = ">=3.12"
license = "Apache-2.0"
authors = [
  {name = "Mark Keller"}
]
readme = "README.md"
description = "Shared utilities used by the pluot_bound and pluot_widget packages. Pure python package."
dependencies = [
  "numpy>=2",
  "zarr>=3",
  "fsspec[http]",
  "requests",
  "aiohttp"
]

[project.urls]
repository = "https://github.com/keller-mark/pluot"
