[build-system]
requires = ["hatchling", "hatch-jupyter-builder>=0.5.0"]
build-backend = "hatchling.build"

[project]
name = "pluot_widget"
version = "0.1.19"
requires-python = ">=3.12"
license = "Apache-2.0"
authors = [
  {name = "Mark Keller"}
]
readme = "README.md"
description = "AnyWidget for rendering Pluot visualizations client-side via WebAssembly"
dependencies = [
  "pluot_core==0.1.19",
  "zarr>=3",
  "anywidget==0.11.0",
  "traitlets",
]

[project.urls]
repository = "https://github.com/keller-mark/pluot"

[tool.hatch.build]
artifacts = ["src/pluot_widget/static/*"]

[tool.hatch.build.targets.sdist]
exclude = ["node_modules"]

[tool.hatch.build.hooks.jupyter-builder]
build-function = "hatch_jupyter_builder.npm_builder"
ensured-targets = ["src/pluot_widget/static/widget.js"]
skip-if-exists = ["src/pluot_widget/static/widget.js"]
dependencies = ["hatch-jupyter-builder>=0.5.0"]

[tool.hatch.build.hooks.jupyter-builder.build-kwargs]
npm = "pnpm"
build_cmd = "build"
