#!/usr/bin/env bash
# Generates the fixtures consumed by the Python/R render-to-script
# integration tests:
#   - render_script.py / render_script.R: source code generated by
#     `pluot_cli` from scripts/fixtures/render_script_integration_layers.json,
#     via `GraphicsFormat::ScriptPython`/`ScriptR` (see `render_to_script` in
#     crates/pluot_core/src/render_script.rs).
#   - canonical.svg: the reference SVG that executing either generated script
#     should reproduce (the already-blessed
#     crates/pluot/tests/snaps-blessed/test_render_script_integration.svg
#     snapshot, produced from the same plot definition).
#
# Usage: scripts/gen_render_script_fixtures.sh [out_dir]
# Prints the resolved out_dir (default: target/render_script_fixtures) to
# stdout on success.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="${1:-"$REPO_ROOT/target/render_script_fixtures"}"

mkdir -p "$OUT_DIR"

>&2 echo "Building pluot_cli..."
# Share the workspace's target dir so already-built dependencies (pluot_core
# itself included) are reused instead of recompiled.
CARGO_TARGET_DIR="$REPO_ROOT/target" cargo build --quiet \
  --manifest-path "$REPO_ROOT/examples/pluot_cli/Cargo.toml"

CLI="$REPO_ROOT/target/debug/pluot_cli"

# The same plot (a PointLayer + AxisLinearLayer) used by
# `plot_params()` in crates/pluot/tests/test_utils/render_script_integration.rs,
# transcribed into pluot_cli's JSON input shape + CLI flags.
COMMON_ARGS=(
  --input "$REPO_ROOT/scripts/fixtures/render_script_integration_layers.json"
  --width 640
  --height 480
  --camera-view "0.15,0,0,0,0,0.15,0,0,0,0,1,0,0,0,0,1"
  --margin-left 60
  --plot-id plot_1
)

>&2 echo "Generating render_script.py..."
"$CLI" "${COMMON_ARGS[@]}" --output "$OUT_DIR/render_script.py"

>&2 echo "Generating render_script.R..."
"$CLI" "${COMMON_ARGS[@]}" --output "$OUT_DIR/render_script.R"

cp "$REPO_ROOT/crates/pluot/tests/snaps-blessed/test_render_script_integration.svg" "$OUT_DIR/canonical.svg"

echo "$OUT_DIR"
