name: Unit tests

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  plain_rust_unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    - uses: Swatinem/rust-cache@v2
    - name: Compile Rust code
      run: cargo build --verbose
    - name: Run Rust unit tests
      # Rendering tests do not work on non-macos runners since they lack GPUs.
      run: cargo test --verbose --features lacks_gpu

  plain_rust_check_examples:
    runs-on: ubuntu-latest
    needs: [plain_rust_unit_tests]
    strategy:
      matrix:
        example_dir: [pluot_cli, pluot_http, pluot_egui, pluot_slint]
        # TODO: include more examples here as they are developed
        # or auto-detect subdirectories of examples/
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - run: sudo apt install -y libfontconfig1-dev
        if: ${{ matrix.example_dir == 'pluot_slint' }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: Compile Example
        run: cargo check --verbose
        working-directory: ./examples/${{ matrix.example_dir }}

  py_compile:
    runs-on: ubuntu-latest
    needs: [plain_rust_unit_tests]
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true
    - uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
      env:
        UV_PYTHON: '3.12'
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    - uses: Swatinem/rust-cache@v2
    # Python-specific stuff
    - name: Install dependencies
      run: uv sync --extra dev
    - name: Compile Rust code
      run: uv run maturin develop --features python

  rlang_compile:
    runs-on: ubuntu-latest
    needs: [plain_rust_unit_tests]
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    - uses: Swatinem/rust-cache@v2
    - uses: r-lib/actions/setup-pandoc@v2
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'release'
        use-public-rspm: true
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::rcmdcheck
        needs: check
        working-directory: bindings-r
    - uses: r-lib/actions/check-r-package@v2
      with:
        working-directory: bindings-r
        error-on: '"error"'
        args: 'c("--no-vignettes")'

  py_and_wasm_unit_tests:
    # We use a macOS runner for tests that rely on the GPU.
    runs-on: macos-latest
    # But we only run these macOS-dependent tests if the previous jobs succeeded.
    needs: [py_compile]
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true
    - uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
      env:
        UV_PYTHON: '3.12'
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: wasm32-unknown-unknown
    # Install clang/LLVM to fix errors with zstd crate compilation for wasm32-unknown-unknown target.
    - name: Install clang via Brew
      run: brew install cmake && brew install llvm
    - name: Set clang path
      run: echo "CC=$(brew --prefix llvm)/bin/clang" >> $GITHUB_ENV
    - name: Set llvm-ar path
      run: echo "AR=$(brew --prefix llvm)/bin/llvm-ar" >> $GITHUB_ENV
    # End troubleshooting zfp-sys and zstd.
    - uses: Swatinem/rust-cache@v2
    # Python-specific stuff
    - name: Install dependencies
      run: uv sync --extra dev
    - name: Compile Rust code
      run: uv run maturin develop --features python
    - name: Run Python unit tests
      run: uv run pytest
    # End Python-specific stuff
    # Start WASM-specific stuff
    - uses: nanasess/setup-chromedriver@master
    #- name: Install wasm-pack (alternative method)
    #  run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Install wasm-pack
      uses: taiki-e/install-action@v2
      with:
        tool: wasm-pack
    - name: Install nightly wasm-bindgen CLI
      run: cargo install --git https://github.com/rustwasm/wasm-bindgen --rev b766ac3e206a8efab2c7cf91923cd502b2bc77a5 wasm-bindgen-cli
    #- uses: Swatinem/rust-cache@v2
    - name: Compile Rust code to WASM
      run: wasm-pack build crates/pluot --release --target web
    - name: Run unit tests
      run: wasm-pack test --headless --chrome crates/pluot
    # Ensure that WASM bundle size is below some threshold.
    - name: Check WASM bundle size
      run: |
        # Get size in bytes
        WASM_SIZE=$(stat -f%z "crates/pluot/pkg/pluot_bg.wasm")
        WASM_SIZE_THRESHOLD=4000000 # 4MB in bytes

        if [ "$WASM_SIZE" -gt "$WASM_SIZE_THRESHOLD" ]; then
          echo "Error: File is too large ($WASM_SIZE bytes). Limit is $WASM_SIZE_THRESHOLD bytes."
          exit 1
        fi
        echo "File size check passed ($WASM_SIZE bytes)."
