name: WASM via wasm-pack

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  unit_tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    # Checkout fork of Zarrs without Rayon iterators
    - uses: actions/checkout@v4
      with:
        repository: keller-mark/zarrs
        ref: keller-mark/no-sync-or-send
        path: ./zarrs

    - uses: nanasess/setup-chromedriver@master
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: wasm32-unknown-unknown
    #- name: Install wasm-pack (alternative method)
    #  run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Install wasm-pack
      uses: taiki-e/install-action@v2
      with:
        tool: wasm-pack
    - uses: Swatinem/rust-cache@v2
    - name: Compile Rust code to WASM
      run: wasm-pack build --target web -- --features wasm
    - name: Run unit tests
      run: wasm-pack test --headless --chrome